mutation {
    a: createWord(
      data: {"word":"a","letters":[{"letter":"a","occurrence":1}],"length":1}
    ) {
      word
      letters {
        letter
        occurrence
      }
      length
    }
    aa: createWord(
      data: {"word":"aa","letters":[{"letter":"a","occurrence":2}],"length":2}
    ) {
      word
      letters {
        letter
        occurrence
      }
      length
    }
    aaa: createWord(
      data: {"word":"aaa","letters":[{"letter":"a","occurrence":3}],"length":3}
    ) {
      word
      letters {
        letter
        occurrence
      }
      length
    }
    aah: createWord(
      data: {"word":"aah","letters":[{"letter":"a","occurrence":2},{"letter":"h","occurrence":1}],"length":3}
    ) {
      word
      letters {
        letter
        occurrence
      }
      length
    }
    
  }