type Letter @embedded {
  letter: String! @unique
  occurrence: Int!
}

type Word @collection(name: "Word") {
  word: String! @unique
  letters: [Letter!]!
  length: Int!
}

input LetterInput {
  letter: String!
  occurrence: Int!
}

type Query {
  GetWordByLength(length: Int!): [Word]
  GetWordByLetter(letters: [LetterInput!]!): Word @resolver(name: "word_retriever")
}